import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  // Recording...
  await page.goto('https://b2b-io--cpqsitdelo.sandbox.my.salesforce.com/');
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).press('ControlOrMeta+v');
  await page.getByRole('textbox', { name: 'Username' }).fill('tester.sales@b2bcpq.sit
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).press('ControlOrMeta+v');
  await page.getByRole('textbox', { name: 'Username' }).fill('tester.sales@b2bcpq.sit');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Tester@@2026');
  await page.getByRole('button', { name: 'Log In to Sandbox' }).click();
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).press('ControlOrMeta+v');
  await page.getByRole('textbox', { name: 'Username' }).fill('tester.sales@b2bcpq.sit');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Tester2026');
  await page.getByRole('button', { name: 'Log In to Sandbox' }).click();');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Tester@@2026');
  await page.getByRole('button', { name: 'Log In to Sandbox' }).click();
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).press('ControlOrMeta+v');
  await page.getByRole('textbox', { name: 'Username' }).fill('114.4.100.222');
  await page.getByRole('textbox', { name: 'Username' }).press('ControlOrMeta+z');
  await page.getByRole('textbox', { name: 'Username' }).fill('');
        await page.goto('https://b2b-io--cpqsitdelo.sandbox.lightning.force.com/lightning/r/Quote/0Q0MR000001PXg90AG/view');
        await expect(page.getByRole('button', { name: 'Create Contract' })).toBeVisible();
        await page.locator('.slds-grid.slds-page-header__detail-row').click();
        await page.locator('div').filter({ hasText: /^FollowCreate ContractGenerate Quote DocumentStart SyncShow more actions$/ }).nth(3).press('ControlOrMeta+r');
        await page.getByRole('button', { name: 'Create Contract' }).click();
        await page.locator('iframe[name="vfFrameId_1778141987289"]').contentFrame().getByRole('button', { name: ' Generate' }).click();
        await page.locator('iframe[name="vfFrameId_1778142314233"]').contentFrame().getByRole('button', { name: 'Go Back to Contract' }).click();
        await page.locator('iframe[name="vfFrameId_1778142322798"]').contentFrame().getByRole('button', { name: ' Generate' }).click();
        await page.locator('iframe[name="vfFrameId_1778142336441"]').contentFrame().getByLabel('Select a Document Template').selectOption('object:10');
        await expect(page.locator('iframe[name="vfFrameId_1778142336441"]').contentFrame().getByText('Error Exception (400): List')).toBeVisible();
        await expect(page.locator('iframe[name="vfFrameId_1778142336441"]').contentFrame().getByRole('button', { name: 'Close' })).toBeVisible();
        await expect(page.locator('iframe[name="vfFrameId_1778142336441"]').contentFrame().getByRole('button', { name: 'Close' })).toBeVisible();
        await expect(page.locator('iframe[name="vfFrameId_1778142336441"]').contentFrame().getByRole('button').nth(5)).toBeVisible();
        await expect(page.locator('iframe[name="vfFrameId_1778142336441"]').contentFrame().getByRole('button').nth(5)).toBeVisible();
        await expect(page.locator('iframe[name="vfFrameId_1778142336441"]').contentFrame().getByRole('button').nth(5)).toBeVisible();
        await expect(page.locator('iframe[name="vfFrameId_1778142336441"]').contentFrame().getByRole('button', { name: 'Close' })).toBeVisible();
        await expect(page.locator('iframe[name="vfFrameId_1778142336441"]').contentFrame().getByRole('button', { name: 'Close' })).toBeVisible();
        await expect(page.locator('iframe[name="vfFrameId_1778142336441"]').contentFrame().getByRole('button', { name: 'Close' })).toBeVisible();
        await expect(page.locator('iframe[name="vfFrameId_1778142336441"]').contentFrame().getByRole('button', { name: 'Close' })).toBeVisible();
        await expect(page.locator('iframe[name="vfFrameId_1778142336441"]').contentFrame().locator('div').filter({ hasText: 'Close' }).nth(3)).toBeVisible();
        await expect(page.locator('iframe[name="vfFrameId_1778142336441"]').contentFrame().getByRole('button').nth(5)).toBeVisible();
        await page.locator('iframe[name="vfFrameId_1778142336441"]').contentFrame().getByRole('button').nth(5).click();
        await page.locator('iframe[name="vfFrameId_1778142336441"]').contentFrame().getByRole('button', { name: 'Go Back to Contract' }).click();
        await expect(page.locator('iframe[name="vfFrameId_1778142336441"]').contentFrame().getByRole('heading', { name: 'Check in document?' })).toBeVisible();
        await expect(page.locator('iframe[name="vfFrameId_1778142336441"]').contentFrame().getByRole('button', { name: 'Yes, Check in' })).toBeVisible();
        await expect(page.locator('iframe[name="vfFrameId_1778142336441"]').contentFrame().getByRole('button', { name: 'Yes, Check in' })).toBeVisible();
        await expect(page.locator('iframe[name="vfFrameId_1778142336441"]').contentFrame().getByRole('button', { name: 'Yes, Check in' })).toBeVisible();
        await expect(page.locator('iframe[name="vfFrameId_1778142336441"]').contentFrame().locator('div').filter({ hasText: 'Are you done with your' }).nth(3)).toBeVisible();
        await page.locator('iframe[name="vfFrameId_1778142336441"]').contentFrame().getByRole('button', { name: 'Yes, Check in' }).click();
        await page.getByTitle('Negotiating').click();
        await page.getByRole('button', { name: 'Edit Status' }).click();
        await page.getByRole('combobox', { name: 'Status' }).click();
        await page.locator('flexipage-record-home-with-subheader-template-desktop2 > div > .slds-grid').click();
        await page.getByRole('combobox', { name: 'Status' }).click();
        await page.getByRole('option', { name: 'Draft' }).click();
        await page.getByRole('option', { name: 'Draft' }).click();
        await page.getByRole('option', { name: 'Draft' }).click();
        await page.getByRole('option', { name: 'Draft' }).click();
        await page.getByRole('button', { name: 'Cancel' }).click();
        await page.getByRole('button', { name: 'Edit Contract Start Date' }).click();
        await page.getByRole('textbox', { name: 'Contract Start Date' }).click();
        await page.getByRole('button', { name: '8', exact: true }).click();
        await page.getByRole('spinbutton', { name: 'Contract Term (months)' }).click();
        await page.getByRole('spinbutton', { name: 'Contract Term (months)' }).fill('12');
        await page.locator('flexipage-record-home-with-subheader-template-desktop2 > div > .slds-grid').click();
        await page.getByRole('button', { name: 'Save' }).click();
        await page.getByTitle('Negotiating').click();
        await page.getByRole('button', { name: 'Edit Status' }).click();
        await page.getByRole('combobox', { name: 'Status' }).click();
        await page.getByRole('option', { name: 'Negotiating' }).click();
        await page.getByRole('option', { name: 'Negotiating' }).click();
        await page.getByRole('option', { name: 'Negotiating' }).click();
        await page.getByRole('button', { name: 'Cancel' }).click();
        await page.getByRole('button', { name: 'Edit', exact: true }).click();
        await page.getByRole('combobox', { name: 'Status' }).click();
        await page.getByRole('option', { name: 'Negotiating' }).click();
        await page.getByRole('button', { name: 'Save', exact: true }).click();
        await page.getByRole('button', { name: 'Current Status: Draft' }).click();
        await page.getByRole('combobox', { name: 'Target State' }).click();
        await page.getByRole('combobox', { name: 'Target State' }).click();
        await page.getByRole('button', { name: 'Execute Transition' }).click();
        await page.getByText('Sfdclogo×Sorry to').press('ControlOrMeta+r');
        await page.getByText('Sfdclogo×Sorry to').press('ControlOrMeta+r');
        await page.getByRole('button', { name: 'Edit', exact: true }).click();
        await page.getByRole('combobox', { name: 'Status' }).click();
        await page.getByRole('option', { name: 'Draft' }).click();
        await page.getByRole('button', { name: 'Save', exact: true }).click();
        await page.getByText('Cancel', { exact: true }).click();
        await expect(page.getByRole('button', { name: 'Upload Document' })).toBeVisible();
        await page.getByRole('button', { name: 'Upload Document' }).click();
        await page.getByRole('combobox', { name: 'Select Document Type' }).click();
        await page.getByRole('option', { name: 'FAB' }).click();
        await page.getByText('Upload Files').click();
        await page.getByRole('button', { name: 'Select a file Upload Files Or' }).setInputFiles('chat_transcript.pdf');
        await page.getByRole('button', { name: 'Upload', exact: true }).click();
        await page.getByRole('tab', { name: 'Related' }).click();
        await expect(page.getByRole('link', { name: 'Links (1)' })).toBeVisible();
        await page.getByRole('tab', { name: 'Details' }).click();
        await page.getByRole('button', { name: 'Close' }).click();
        await page.locator('#window').click();
        await page.getByRole('button', { name: 'Show more actions' }).click();
        await page.getByRole('tab', { name: 'Related' }).click();
        await page.getByRole('button', { name: 'Close' }).click();
        await page.getByRole('button', { name: 'Close' }).click();
        await page.getByRole('button', { name: 'Close' }).click();
        await page.getByRole('gridcell', { name: 'Select Item' }).nth(1).click();
        await page.getByRole('button', { name: 'Close' }).click();
        await page.getByRole('link', { name: '00000249' }).click();
        await page.getByRole('rowheader', { name: 'Open 00000249 Preview' }).click();
        await page.getByRole('link', { name: '00000249' }).click();
        await page.getByRole('button', { name: 'Close' }).click();
        await page.getByRole('button', { name: 'Close' }).click();
        await page.getByRole('tab', { name: 'Related' }).click();
        await page.getByRole('button', { name: 'Close' }).click();
        await page.getByRole('button', { name: 'Show Actions' }).nth(3).click();
        await page.getByRole('link', { name: '2026-05-07_15-33-42_chat_transcript.pdf', exact: true }).click();
        await page.getByRole('rowheader', { name: '2026-05-07_15-33-' }).locator('#window').click();
        await page.goto('https://b2b-io--cpqsitdelo.sandbox.lightning.force.com/lightning/r/Contract/800MR00000AMNMoYAP/view');
        await page.getByRole('button', { name: 'Current Status: Negotiating' }).click();
        await page.getByRole('button', { name: 'Execute Transition' }).click();
        await page.goto('https://b2b-io--cpqsitdelo.sandbox.lightning.force.com/lightning/r/Contract/800MR00000AMNMoYAP/view');
        await expect(page.getByRole('button', { name: 'Submit for Approval' })).toBeVisible();
        await page.getByRole('button', { name: 'Submit for Approval' }).click();
        await page.getByRole('button', { name: 'Submit' }).click();
        await page.getByRole('button', { name: 'Notifications' }).click();
        await page.getByRole('link', { name: 'Approval request for the quote is approved API Test Quote 1777890904595 an hour' }).click();
        await page.goto('https://b2b-io--cpqsitdelo.sandbox.lightning.force.com/lightning/r/Contract/800MR00000AMNMoYAP/view');
        await page.getByRole('tab', { name: 'Related' }).click();
        await page.getByRole('button', { name: 'Current Status: Customer' }).click();
        await page.getByRole('combobox', { name: 'Target State' }).click();
        await page.getByRole('option', { name: 'Signed' }).click();
        await page.getByRole('option', { name: 'Signed' }).click();
        await page.getByRole('option', { name: 'Signed' }).click();
        await page.getByRole('combobox', { name: 'Target State' }).click();
        await page.getByRole('combobox', { name: 'Target State' }).click();
        await page.getByRole('option', { name: 'Signed' }).click();
        await page.getByRole('option', { name: 'Signed' }).click();
        await page.getByRole('option', { name: 'Signed' }).click();
        await page.getByRole('button', { name: 'Execute Transition' }).click();
        await page.goto('https://b2b-io--cpqsitdelo.sandbox.lightning.force.com/lightning/r/Contract/800MR00000AMNMoYAP/view');
        await expect(page.getByRole('button', { name: 'Enterprise Quote' })).toBeVisible();
        await expect(page.getByRole('button', { name: 'Check Eligiblity' })).toBeVisible();
        await page.getByRole('button', { name: 'Check Eligiblity' }).click();
        await page.getByRole('button', { name: 'Check Eligibility' }).click();
        await expect(page.locator('div').filter({ hasText: 'Error notification.Not' }).nth(3)).toBeVisible();

        // sebelum check eligibility harus update account fields:
        // CPQ_Collection_Status__c = CLEARED
        // CPQ_Collection_Status_Date__c <= 24 jam
        await page.getByRole('button', { name: 'Check Eligiblity' }).click();
        await page.getByRole('button', { name: 'Check Eligibility' }).click();
        await expect(page.locator('div').filter({ hasText: 'Success notification.' }).nth(3)).toBeVisible();
        await page.locator('#action button').filter({ hasText: 'Show menu' }).click();
        await page.locator('li').filter({ hasText: 'Activate' }).click();
        await page.locator('li').filter({ hasText: 'Activate' }).click();
        await page.locator('a').filter({ hasText: 'Activate' }).click();

        // berhasil di-activate

        // mulai create order
        await page.locator('button').filter({ hasText: 'Create Order' }).click();
        await page.goto('https://b2b-io--cpqsitdelo.sandbox.lightning.force.com/lightning/r/Order/801MR00000BbPsSYAV/view');

        // cek ke related ke sub order
        // ubah status ke Ready to Submit
        await page.goto('https://b2b-io--cpqsitdelo.sandbox.my.salesforce.com/?ec=302&startURL=%2Fvisualforce%2Fsession%3Furl%3Dhttps%253A%252F%252Fb2b-io--cpqsitdelo.sandbox.lightning.force.com%252Flightning%252Fr%252FOrder%252F801MR00000BbPsSYAV%252Fview');
        await page.getByRole('textbox', { name: 'Username' }).click();
        await page.getByRole('textbox', { name: 'Username' }).fill('o.harliansyah@ioh.co.id.cpqsitdelo');
        await page.getByRole('textbox', { name: 'Password' }).click();
        await page.getByRole('textbox', { name: 'Password' }).fill('QFbe3fqe1osXwA');
        await page.getByRole('button', { name: 'Log In to Sandbox' }).click();
        await page.goto('https://b2b-io--cpqsitdelo.sandbox.lightning.force.com/lightning/r/Order/801MR00000BbPsSYAV/view');
        await page.getByRole('tab', { name: 'Related' }).click();
        await expect(page.getByRole('heading', { name: 'Orders (1)' })).toBeVisible();
        await page.getByRole('link', { name: '00094725' }).click();
        await page.getByRole('button', { name: 'Close' }).click();
        await page.getByRole('button', { name: 'Close' }).click();
        await page.getByRole('button', { name: 'Close' }).click();
        await page.getByRole('button', { name: 'Close' }).click();
        await page.getByRole('rowheader', { name: 'Open 00094725 Preview' }).click();
        await page.getByRole('rowheader', { name: 'Open 00094725 Preview' }).click();
        await page.getByRole('button', { name: 'Close' }).click();
        await page.getByRole('button', { name: 'Close' }).click();
        await page.getByRole('button', { name: 'Close' }).click();
        await page.getByRole('button', { name: 'Show Actions' }).click();
        await page.locator('span').filter({ hasText: '00094725Open 00094725 Preview' }).click();
        await page.getByRole('link', { name: '00094725' }).click();
        await page.getByLabel('Orders').getByRole('link', { name: '00094725' }).click();
        await expect(page.getByRole('button', { name: 'Submit Order' })).toBeVisible();
        await page.getByRole('button', { name: 'Submit Order' }).click();
        await page.goto('https://b2b-io--cpqsitdelo.sandbox.lightning.force.com/lightning/r/vlocity_cmt__OrchestrationPlan__c/a67MR0000000IOLYA2/view');
        await expect(page.locator('records-entity-label').filter({ hasText: 'Orchestration Plan' })).toBeVisible();
});